resources:
- name: self-update-src
  type: git
  source:
    uri: https://github.com/sursmobil/concourse-self-update.git

- name: ci-src
  type: git
  source: ((src-repo))

- name: self-update-docker
  type: docker-image
  source: ((docker-repo))

jobs:
- name: build-self-update-docker
  plan:
  - get: self-update-src
  - put: self-update-docker
    params:
      build: self-update-src/image
      build_args:
        concourse_url: ((concourse-url))

- name: update-pipelines
  plan:
  - aggregate:
    - get: self-update-src
    - get: self-update-docker
      passed:
      - build-self-update-docker
    - get: ci-src
      trigger: true

  - task: set-pipelines
    file: self-update-src/tasks/set-pipelines.yml
    image: self-update-docker
    params:
      CONCOURSE_URL: ((concourse-url))
      CONCOURSE_LOGIN: ((concourse-login))
      SELF_UPDATE_NAME: ((name))
